#Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URL}:8761/eureka/
#OAuth Authentication
security:
  oauth2:
    resource:
      user-info-uri: http://${AUTH_SERVER_URL}:8013/user
